'use strict';
const $=id=>document.getElementById(id);
const COL={buy_smart:'买得明白',classic_rediscovery:'经典再发现',behind_the_game:'作品背后'};
const FORM={deals:'精选折扣',ratings:'评分筛选',new_game:'新游前瞻',classic:'经典回顾',detail:'细节拆解',creator:'制作人故事',ranking:'有界榜单'};
const FC={deals:'buy_smart',ratings:'buy_smart',new_game:'buy_smart',classic:'classic_rediscovery',detail:'classic_rediscovery',creator:'behind_the_game',ranking:'behind_the_game'};
const STATUS={backlog:'选题待定',needs_research:'待补证',brief_ready:'简报就绪',draft_ready:'待审初稿',in_review:'审核中',approved:'已审核',scheduled:'已排期',published:'已发布',out_of_scope:'不合受众',blocked:'暂停处理',expired:'已过期',archived:'已归档'};
const SOURCE={steam_store:'Steam 商店',steam_news:'游戏新闻 / 公告',steam_reviews:'Steam 评价',epic:'Epic 限免',reddit:'Reddit 社区',official_rss:'自定义 RSS',xiaoheihe:'小黑盒公开页',example:'演示资料'};
const SRCSTATUS={ok:'已读取',partial:'部分读取',empty:'本次为空',not_configured:'未配置 / 关闭',needs_access:'需要权限',rate_limited:'来源限流',failed:'读取失败'};
const CLAIM={fact:'可观察事实',inference:'编辑推论',opinion:'明确主观看法',quote:'原始引语',price:'价格',rating:'评分统计',role:'作品职务',detail:'细节复现',design_intent:'设计意图',historical_low:'历史低价',free_offer:'免费活动',ranking:'排名口径'};
const VIEWS={dashboard:'今日工作台',topics:'选题库',subjects:'题材与资料',calendar:'排期与发布',analytics:'数据复盘',settings:'设置与来源',legacy:'旧版归档'};
const state={mode:'live',view:'dashboard',meta:null,dash:null,brief:null,tab:'brief',conn:'checking',jobId:null,polling:null,dirty:false,filterPool:'all',filterColumn:'',filterStatus:'',search:'',cacheNotice:false,subjects:[]};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=x=>x?new Date(x).toLocaleString('zh-CN',{hour12:false}):'—';
const options=(obj,value)=>Object.entries(obj).map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('');
const tag=(text,kind='')=>`<span class="tag ${kind}">${esc(text)}</span>`;
const safeUrl=x=>{try{const u=new URL(x);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const link=(u,t='打开来源')=>safeUrl(u)?`<a href="${esc(safeUrl(u))}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`:'<span class="subtle">来源地址待补</span>';
const modePath=p=>p+(p.includes('?')?'&':'?')+'mode='+state.mode;
function toast(text){$('toast').textContent=text;$('toast').classList.add('on');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('on'),6000);}
function errorText(e){return e?.message||String(e);}
async function api(path,opt={}){
 const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),25000);
 try{
  const res=await fetch(path,{...opt,headers:{'Content-Type':'application/json','X-Heybox-Token':state.meta?.csrf_token||'',...opt.headers},signal:ctrl.signal});
  let data;try{data=await res.json();}catch{throw new Error('服务未返回JSON。请从本地启动入口打开，不要双击HTML文件。');}
  if(!res.ok){let detail=data.detail;if(Array.isArray(detail))detail=detail.map(d=>d.msg).join('；');throw new Error(detail||'请求失败（'+res.status+'）');}
  return data;
 }catch(e){if(e.name==='AbortError')throw new Error('服务响应超时，请查看运行状态；不要反复提交同一操作。');if(e instanceof TypeError){setConnection('disconnected');throw new Error('本地服务连接中断。编辑内容保留在浏览器缓存，请重新双击启动。');}throw e;}finally{clearTimeout(timer);}
}
const post=(p,x)=>api(modePath(p),{method:'POST',body:JSON.stringify(x)});
const put=(p,x)=>api(modePath(p),{method:'PUT',body:JSON.stringify(x)});
function setConnection(status){state.conn=status;$('connection').className='connection '+status;$('connectionText').textContent={checking:'正在连接',ready:'服务正常',busy:'任务运行中',disconnected:'服务已断开'}[status];$('connectionBanner').hidden=status!=='disconnected';if(status==='disconnected')$('connectionBanner').innerHTML='本地服务已断开。请双击 <b>scripts/start-web.command</b> 重新启动，页面将自动重连。未保存的编辑仅在此浏览器缓存中。';document.querySelectorAll('[data-action="run"]').forEach(b=>b.disabled=status!=='ready');}
let healthBusy=false;
async function health(){
 if(healthBusy)return;healthBusy=true;
 try{const r=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(3500)});const info=await r.json();if(!r.ok||info.service!=='heybox-content-studio')throw new Error('wrong service');const prev=state.conn;setConnection(info.status==='busy'?'busy':'ready');if(prev==='disconnected'||!state.meta){state.meta=await api('/api/meta');await refresh(false);}if(info.active_job&&!state.polling){watchJob(info.active_job.id);} }
 catch{setConnection('disconnected');}finally{healthBusy=false;}
}
async function refresh(render=true){state.dash=await api(modePath('/api/dashboard'));$('navCount').textContent=state.dash.stats.total;if(render)await renderView();}
function header(kicker,title,sub,actions=''){return `<div class="page-title"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="intro">${esc(sub)}</p></div><div class="row">${actions}</div></div>`;}
function button(text,action,kind='',extra=''){return `<button class="btn ${kind}" data-action="${action}" ${extra}>${text}</button>`;}
function empty(title,message,actions=''){return `<div class="empty"><span class="empty-symbol">▤</span><h3>${esc(title)}</h3><p>${esc(message)}</p><div class="row" style="justify-content:center">${actions}</div></div>`;}
function stat(label,value,suffix){return `<div class="stat"><div class="stat-label">${esc(label)}</div><div class="stat-number">${esc(value)}<small>${esc(suffix)}</small></div></div>`;}
function jobbar(){return state.jobId?`<div class="jobbar"><span class="spinner"></span><span id="jobMessage">任务正在处理，切换页面不会取消任务…</span></div>`:'';}
function sourceRows(run){return run?.sources?.length?run.sources.map(s=>`<div class="source-row"><span>${esc(SOURCE[s.name]||s.name)}${s.warnings?.length?`<small>${esc(s.warnings[0]).slice(0,260)}</small>`:''}</span><span>${tag(SRCSTATUS[s.status]||s.status,s.status==='ok'?'good':s.status==='not_configured'?'':'warn')} <small>${s.count??'—'}条</small></span></div>`).join(''):'<p class="small muted">还未运行来源采集。这不代表没有可用选题。</p>';}
function pickCard(b,index){
 const type=index===0?'轻内容 · 买得明白':'主栏目 · 常青研究';
 if(!b)return `<section class="panel recommendation"><div class="kicker">${type}</div><h3>${index===0?'不凑篇数，先把依据补齐。':'没有大新闻，也有好问题。'}</h3><p>${index===0?'当前没有符合受众、证据和时间预算的就绪选题。去选题库查看具体缺口。':'经典游戏、设计细节和开发故事可以提前研究。已有资料不会因为隔天而被清空。'}</p><div class="row">${button(index===0?'查看待补证选题':'查看常青题库',index===0?'needs-research':'evergreen','ghost tiny')}</div></section>`;
 return `<section class="panel recommendation"><div class="row between"><div class="kicker">${esc(COL[b.column])} · ${b.pool==='evergreen'?'常青':'时效'}</div>${tag('资料齐备','good')}</div><h3>${esc(b.title)}</h3><p>${esc(b.reader_question||b.reader_value)}</p><div class="row between"><div>${tag(FORM[b.content_form])} <small>预计 ${b.estimated_human_minutes??'—'} 分钟</small></div>${button('打开简报 →','open','primary tiny',`data-id="${b.id}"`)}</div></section>`;
}
function topicRows(rows){return rows.map(b=>`<tr><td><button class="topic-title" data-action="open" data-id="${b.id}">${esc(b.title)}</button><small>${esc(b.reader_question||'先明确一个读者问题')}</small></td><td>${tag(COL[b.column],b.column==='buy_smart'?'good':b.column==='classic_rediscovery'?'blue':'warn')}<small>${esc(FORM[b.content_form])} · ${b.pool==='evergreen'?'常青':'时效'}</small></td><td>${tag(STATUS[b.status],b.approval_valid?'good':'')}<small>${b.priority.verified_claims}/${b.priority.required_claims} 条核心事实已核验</small></td><td><span class="priority">${b.priority.total}</span><small>编辑优先级</small></td><td>${b.estimated_human_minutes??'—'} <small>预计分钟</small></td></tr>`).join('');}
function topicTable(rows){return rows.length?`<div class="table-scroll"><table><thead><tr><th>选题与读者问题</th><th>栏目</th><th>进度 / 证据</th><th>优先级</th><th>人工成本</th></tr></thead><tbody>${topicRows(rows)}</tbody></table></div>`:empty('还没有符合条件的选题','新建一个具体问题，或载入待研究角度。它们只是研究起点，不是假成稿。',button('新建选题','new','primary')+button('载入12个角度种子','seeds','ghost'));}
function filtered(){return (state.dash?.briefs||[]).filter(b=>(state.filterPool==='all'||b.pool===state.filterPool)&&(state.filterColumn===''||b.column===state.filterColumn)&&(state.filterStatus===''||b.status===state.filterStatus)&&(!state.search||(b.title+' '+b.reader_question+' '+b.angle).toLowerCase().includes(state.search.toLowerCase())));}
async function renderView(){
 $('viewName').textContent=VIEWS[state.view];document.querySelectorAll('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('exampleBanner').hidden=state.mode!=='example';
 if(!state.dash){$('view').innerHTML=empty('正在连接本地编辑台','首次运行需要先启动本地服务。');return;}
 const d=state.dash;
 if(state.view==='dashboard'){
  const rec=d.recommended_ids.map(id=>d.briefs.find(b=>b.id===id));
  $('view').innerHTML=header('EDITORIAL WORKSPACE','把好选题，变成好内容。','先找一个值得回答的问题，再用事实、材料和你的判断完成一篇帖子。',button('＋ 新建选题','new','ghost')+button('↻ 更新选题池','run','primary'))+jobbar()+
  `<div class="row between"><span class="small subtle">${state.mode==='example'?'示例工作区 · 与真实资料隔离':'真实工作区 · 所有生成结果仍须人工审核'}</span><span class="small subtle">${d.latest_run?'上次采集 '+date(d.latest_run.finished_at):'尚未采集'}</span></div>`+
  `<div class="stats">${stat('待补证选题',d.stats.needs_research,'个')}${stat('资料齐备',d.stats.ready,'个')}${stat('已排期',d.stats.scheduled,'篇')}${stat('已登记发布',d.stats.published,'篇')}</div>`+
  `<div class="section-title"><h2>今天可处理什么？</h2><small>最多两篇 · 证据优先，不强行补位</small></div><div class="two-cols">${pickCard(rec.find(b=>b.pool==='timely'),0)}${pickCard(rec.find(b=>b.pool==='evergreen'),1)}</div>`+
  `<div class="dashboard-bottom"><section class="panel"><div class="panel-head"><div><h2>继续推进你的选题</h2><small>选题不是一次性的热点，每次研究都能留在这里。</small></div>${button('全部选题 →','topics','ghost tiny')}</div>${topicTable(d.briefs.filter(b=>!['archived','published','out_of_scope'].includes(b.status)).slice(0,4))}</section><div><section class="panel pad"><div class="row between" style="margin-bottom:10px"><h3>采集来源</h3>${button('管理','settings','ghost tiny')}</div>${sourceRows(d.latest_run)}</section><section class="panel pad section-gap"><div class="eyebrow">EDITORIAL PRINCIPLE</div><h3>买得明白，玩得更懂。</h3><p class="intro">不编第一人称体验，不用高互动替代事实。AI负责整理和初稿，最后的判断属于你。</p></section></div></div>`;
 }else if(state.view==='topics'){
  $('view').innerHTML=header('TOPIC LIBRARY','一个问题，就是一个起点。','时效与常青分开整理。先写清给谁看、解决什么，再考虑怎么写。',button('载入角度种子','seeds','ghost')+button('＋ 新建选题','new','primary'))+jobbar()+
  `<div class="filters"><div class="segments">${['all','timely','evergreen'].map((p,i)=>`<button data-pool="${p}" class="${state.filterPool===p?'active':''}">${['全部选题','时效事件','常青题库'][i]}</button>`).join('')}</div><input id="topicSearch" aria-label="搜索选题" placeholder="搜索标题、问题或角度…" value="${esc(state.search)}"><select id="columnFilter" aria-label="按栏目筛选"><option value="">全部栏目</option>${options(COL,state.filterColumn)}</select><select id="statusFilter" aria-label="按状态筛选"><option value="">全部进度</option>${options(STATUS,state.filterStatus)}</select></div><section id="topicsTable" class="panel">${topicTable(filtered())}</section>`;
 }else if(state.view==='calendar'){
  const rows=d.briefs.filter(b=>b.status==='scheduled'||b.status==='approved'||b.publications.length).sort((a,b)=>(a.scheduled_at||a.updated_at).localeCompare(b.scheduled_at||b.updated_at));
  $('view').innerHTML=header('PUBLISHING DESK','把完成的稿件，排进日程。','排期只是提醒，不会代你登录或发布。发布后，记录真实帖子链接和采用版本。',button('查看选题库','topics','ghost'))+
  (rows.length?`<section class="panel pad">${rows.map(b=>`<div class="timeline-item"><small>${b.scheduled_at?'计划 '+date(b.scheduled_at):STATUS[b.status]} · ${COL[b.column]}</small><h3>${esc(b.drafts.at(-1)?.title||b.title)}</h3><small>${b.approval_valid?'本版本已审核':'发布前需重新核验'} · ${b.publications.length} 条发布记录</small><div class="row">${button('打开稿件','open-publish','primary tiny',`data-id="${b.id}"`)}${b.publications.map(p=>link(p.url,'查看帖子')).join(' · ')}</div></div>`).join('')}</section>`:empty('还没有排期稿件','通过人工审核的稿件可以排期。时效价格到发布时仍需有效，不会因为排过期而自动通过。',button('去处理选题','topics','primary')));
 }else if(state.view==='analytics'){
  const a=await api(modePath('/api/analytics'));
  $('view').innerHTML=header('EDITORIAL REVIEW','看自己的数据，调整下一篇。','记录发布后24小时、72小时和7天表现，同时保留实际观察时间。没有数据就留空，不补零。')+
  `<div class="grid3">${Object.keys(COL).map(c=>`<div class="panel pad"><span class="small muted">${COL[c]}</span><div class="metric-number">${a.column_counts[c]||0} <small>篇已发布</small></div><div class="meter"><span style="width:${Math.min(100,100*(a.column_counts[c]||0)/Math.max(1,a.publications.length))}%"></span></div><small>真实登记的发布次数</small></div>`).join('')}</div>`+
  `<div class="section-title"><h2>发布表现</h2><small>不能用不同帖子年龄的累计点赞直接排名</small></div>`+
  (a.publications.length?a.publications.map(p=>`<section class="panel pad section-gap"><div class="row between"><div><h3>${esc(p.title)}</h3><small>${date(p.published_at)} · 人工累计 ${p.human_minutes} 分钟 · ${link(p.url,'帖子')}</small></div>${button('记录观察数据','metric','primary tiny',`data-id="${p.brief_id}" data-pub="${p.publication_id}"`)}</div>${p.metrics.length?`<div class="table-scroll section-gap"><table><thead><tr><th>目标窗 / 实际年龄</th><th>阅读</th><th>点赞</th><th>评论</th><th>收藏</th><th>分享</th><th>关注</th></tr></thead><tbody>${p.metrics.map(m=>`<tr><td>${m.window} / ${m.post_age_hours}h ${m.window_mismatch?tag('偏离目标窗','warn'):''}<small>${date(m.observed_at)}</small></td>${['views','likes','comments','favorites','shares','follows'].map(k=>`<td>${m[k]??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="intro">暂无观察记录；无法据此判断效果。</p>'}</section>`).join(''):empty('还没有发布数据','先在稿件里登记帖子链接，再录入平台实际提供的数据。这里不会显示模拟收益或预测播放量。'))+
  `<div class="hint section-gap">${esc(a.insight)} 单篇涨粉必须有可归因数据；一天的总涨粉不能任意分给某篇。</div>`;
 }else if(state.view==='subjects'){
  const subjects=await api(modePath('/api/subjects'));
  $('view').innerHTML=header('SUBJECT & SOURCE LIBRARY','先积累熟悉的题材。','游戏、制作人、工作室和发行商分别记录。熟悉度未知时，不自动建立“资深玩家”人设。',button('导入研究包','import-pack','ghost')+button('＋ 新增题材','subject','primary'))+
  (subjects.length?`<div class="grid3">${subjects.map(s=>`<section class="panel subject-card">${tag({game:'游戏',person:'制作人',studio:'开发工作室',publisher:'发行商',group:'集团'}[s.kind])}<h3>${esc(s.name)}</h3><p>${esc(s.notes||'暂无研究备注')}</p><small>${s.confirmed?'身份已确认':'身份待确认'} · ${{unknown:'熟悉度未知',researched:'已读资料',played:'本人玩过'}[s.familiarity]}</small></section>`).join('')}</div>`:empty('从10–20个熟悉的游戏或系列起步','这里是题材目录。每篇具体职务、价格、访谈和画面仍需要在选题资料包中核验。',button('新增题材','subject','primary')))+
  `<section class="panel pad section-gap"><h3>研究资料跟着问题走</h3><p class="intro">在每个选题中，把来源、主张和素材放在一起。不要堆一百个链接，然后假设AI已经读懂。已有外部研究包可用“导入研究包”载入，所有主张会重置为待核验。</p>${button('打开选题库','topics','ghost tiny')}</section>`;
 }else if(state.view==='legacy'){
  const a=await api('/api/legacy');
  $('view').innerHTML=header('READ-ONLY ARCHIVE','旧资料，不丢失。','旧版日报、人工编辑稿和玩家数据库只读保存，不参与新编辑评分。')+
  (a.files.length?`<section class="panel table-scroll"><table><thead><tr><th>原始路径</th><th>位置</th><th>大小</th><th></th></tr></thead><tbody>${a.files.map(f=>`<tr><td>${esc(f.path)}</td><td>${esc(f.origin)}</td><td>${(f.size/1024).toFixed(1)} KB</td><td><a class="btn tiny" href="/api/legacy/${f.id}">下载原文件</a></td></tr>`).join('')}</tbody></table></section>`:empty('当前目录没有旧版归档','在新目录使用时，请按README中的迁移命令先预览，再复制校验备份。原项目文件不会被删除。'));
 }else if(state.view==='settings'){renderSettings();}
 setConnection(state.conn);
}
function renderSettings(){const s=state.dash.settings,p=state.dash.policy;
 $('view').innerHTML=header('WORKSPACE SETTINGS','为你的编辑节奏配置。','参数是本地编辑建议，不是小黑盒算法或平台承诺。来源失败不影响你处理已有资料。')+
 `<section class="panel settings-section"><h2>工作区</h2><div class="row"><select id="workspaceMode" style="max-width:240px"><option value="live" ${state.mode==='live'?'selected':''}>真实资料库（正式使用）</option><option value="example" ${state.mode==='example'?'selected':''}>示例资料库（不可发布）</option></select>${button('载入示例流程','example','ghost')}${button('无网络测试','offline','ghost')}</div><p class="intro">示例数据、真实数据、离线运行记录按模式分别存储。切换不会清空另一工作区。</p></section>`+
 `<form id="settingsForm"><section class="panel settings-section"><h2>栏目与人工预算</h2><div class="form-grid">${field('reviewer_name','审核人',s.reviewer_name)}${field('audience','默认读者',s.audience)}${numberField('daily_minutes','每日人工预算（分钟）',s.daily_minutes)}${numberField('weekly_minutes','每周人工预算（分钟）',s.weekly_minutes)}${numberField('heavy_posts_per_week','每周重型稿建议上限',s.heavy_posts_per_week)}${numberField('daily_posts_max','每日最多推荐稿件',s.daily_posts_max)}${numberField('mix_buy','买得明白占比（%）',s.column_mix.buy_smart)}${numberField('mix_classic','经典再发现占比（%）',s.column_mix.classic_rediscovery)}${numberField('mix_behind','作品背后占比（%）',s.column_mix.behind_the_game)}${numberField('price_fresh_minutes','发布前价格核验窗口（分钟）',s.price_fresh_minutes)}</div></section>
 <section class="panel settings-section"><h2>发现来源与数据预算</h2><p>勾选来源只是启用适配器，不代表一定能访问。小黑盒静态公开页可能为空；它不是完整热帖爬虫。</p><div class="settings-source-grid">${Object.keys(s.enabled_sources).map(k=>`<label class="check"><input type="checkbox" name="source_${k}" ${s.enabled_sources[k]?'checked':''}>${SOURCE[k]||k}</label>`).join('')}</div><div class="form-grid section-gap">${field('country','Steam / Epic 地区代码',s.country)}${numberField('min_review_count','评价筛选最小样本量',s.min_review_count)}${numberField('max_requests','每轮最多HTTP请求',s.max_requests)}${numberField('request_timeout','单请求超时（秒）',s.request_timeout)}${area('watched_apps','关注Steam游戏（每行 AppID=游戏名）',Object.entries(s.watched_apps).map(([k,v])=>k+'='+v).join('\n'))}${area('subreddits','Reddit社区（每行一个，不含r/）',s.subreddits.join('\n'))}${area('official_rss','RSS来源（每行一个完整URL）',s.official_rss.join('\n'),'full')}</div></section>
 <section class="panel settings-section"><h2>写作辅助</h2><p>默认不调用付费API。可复制研究包给网页AI后导入稿件。Codex模式使用你本机已有CLI认证；不可用时返回大纲，不伪造成稿。</p><div class="form-grid"><div><label>写作方式</label><select name="llm_mode">${options({manual:'网页AI / 手动导入（默认）',codex:'本机Codex CLI',command:'可信外部命令（高级）'},s.llm_mode)}</select></div>${numberField('llm_timeout','模型超时（秒）',s.llm_timeout)}</div><div class="form-actions"><button class="btn primary" type="submit">保存设置</button><small>不保存密钥；外部命令只可通过可信本地环境变量配置。</small></div></section></form>`+
 `<form id="policyForm" class="panel settings-section"><div class="row between"><h2>平台规则检查记录</h2>${tag('激励资格未由系统保证','warn')}</div><p>这里记录你对规则的人工检查，不承诺AI稿符合激励、平台不会限流或具体收入。</p><div class="form-grid">${area('urls','核查规则网址（每行一个）',(p.urls||[]).join('\n'),'full')}${field('reviewer','核查人',p.reviewer)}${field('checked_at','核查时间（含时区，留空表示未核实）',p.checked_at||'')}${area('ai_note','AI辅助说明要求 / 你的备注',p.ai_note,'full')}${area('notes','其他适用说明',p.notes,'full')}</div><div class="form-actions"><button class="btn" type="submit">保存规则记录</button><span class="disabled-note">未核对当期规则时，保持未确认。</span></div></form>`;
}
function field(name,label,value='',cls=''){return `<div class="form-field ${cls}"><label for="f_${name}">${esc(label)}</label><input id="f_${name}" name="${name}" value="${esc(value)}"></div>`;}
function numberField(name,label,value=''){return `<div class="form-field"><label>${esc(label)}</label><input name="${name}" type="number" min="0" value="${esc(value??'')}"></div>`;}
function area(name,label,value='',cls=''){return `<div class="form-field ${cls}"><label>${esc(label)}</label><textarea name="${name}">${esc(value)}</textarea></div>`;}
function selectField(name,label,obj,value){return `<div class="form-field"><label>${esc(label)}</label><select name="${name}">${options(obj,value)}</select></div>`;}
function subjectChoices(b){
 const checked=new Set(b.subject_ids||[]);
 const known=(state.subjects||[]);
 const rows=known.map(s=>`<label class="check"><input type="checkbox" name="subject_ids" value="${esc(s.id)}" ${checked.has(s.id)?'checked':''}>${esc(s.name)} <small>${esc({game:'游戏',person:'制作人',studio:'工作室',publisher:'发行商',group:'集团'}[s.kind])}</small></label>`).join('');
 const unknown=[...checked].filter(id=>!known.some(s=>s.id===id)).map(id=>`<label class="check"><input type="checkbox" name="subject_ids" value="${esc(id)}" checked>待映射题材 ${esc(id)}</label>`).join('');
 return `<div class="form-field full"><label>关联题材（可多选）</label><div class="settings-source-grid">${rows+unknown||'<small>先在「题材与资料」新增游戏 / 制作人，再关联到这个简报。</small>'}</div><small>制作人关联不代表其担任作品的全部职务，具体职务仍单独核验。</small></div>`;
}
let previousFocus=null;
function modal(title,html){previousFocus=document.activeElement;$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modalOverlay').hidden=false;$('modalContent').querySelector('input,textarea,select,button')?.focus();}
function closeModal(){$('modalOverlay').hidden=true;previousFocus?.focus();}
function modalForm(id,body,submit='保存'){return `<form id="${id}"><div class="form-grid">${body}</div><div class="form-actions"><button class="btn primary" type="submit">${submit}</button><button type="button" class="btn ghost" data-action="close-modal">取消</button></div></form>`;}
async function openBrief(id,tab='brief'){
 if(state.brief&&state.dirty&&!confirm('编辑内容尚未保存到磁盘。继续切换会保留浏览器缓存，确认继续？'))return;
 state.brief=await api(modePath('/api/briefs/'+id));state.subjects=await api(modePath('/api/subjects'));state.tab=tab;state.dirty=false;state.cacheNotice=false;$('editorOverlay').hidden=false;document.body.style.overflow='hidden';renderEditor();$('closeEditor').focus();
}
function closeEditor(){if(state.dirty&&!confirm('尚未保存。继续关闭会保留本浏览器缓存，但不会写入磁盘，确认关闭？'))return;$('editorOverlay').hidden=true;document.body.style.overflow='';state.brief=null;state.dirty=false;refresh().catch(e=>toast(errorText(e)));}
const cacheKey=()=>`heybox:${state.meta?.instance}:${state.mode}:${state.brief?.id}:draft`;
function cached(){try{return JSON.parse(localStorage.getItem(cacheKey())||'null');}catch{return null;}}
function currentDraftData(){const b=state.brief;return {title:$('draftTitle')?.value||b.title,body_markdown:$('draftBody')?.value||'',comment_hook:$('commentHook')?.value||'',title_candidates:b.drafts.at(-1)?.title_candidates||[],used_claim_ids:[...document.querySelectorAll('input[name=used_claim]:checked')].map(c=>c.value),assistance:'manual'};}
function markDirty(){if(state.tab!=='draft'||!$('draftBody'))return;state.dirty=true;try{localStorage.setItem(cacheKey(),JSON.stringify({base_version:state.brief.version,saved_at:new Date().toISOString(),draft:currentDraftData()}));$('editorSaveStatus').textContent='已缓存到本浏览器 · 尚未保存到项目磁盘';}catch{$('editorSaveStatus').textContent='浏览器缓存不可用，请尽快保存到磁盘';}}
function draftDefaults(){const b=state.brief;const saved=b.drafts.at(-1);return saved||{title:b.title,body_markdown:'',comment_hook:'',title_candidates:[],used_claim_ids:b.claims.filter(c=>c.status==='verified').map(c=>c.id)};}
function renderEditor(){
 const b=state.brief;if(!b)return;
 $('editorKicker').textContent=COL[b.column]+' / '+FORM[b.content_form]+' / '+(state.mode==='example'?'示例':'真实资料');$('editorHeading').textContent=b.title;$('editorState').textContent=STATUS[b.status];$('editorState').className='tag '+(b.approval_valid?'good':'');
 document.querySelectorAll('[data-tab]').forEach(btn=>{btn.classList.toggle('active',btn.dataset.tab===state.tab);btn.setAttribute('aria-selected',btn.dataset.tab===state.tab);});
 if(state.tab==='brief'){
  $('editorContent').innerHTML=`<div class="hint ${b.priority.ready?'':'warn'}">${b.priority.ready?'核心材料已齐备，可以生成待审稿。':`简报还有 ${b.priority.gaps.length} 项待补。先把问题与依据讲清楚，再生成全文。`}</div><form id="briefForm" class="section-gap"><div class="form-grid">${field('title','选题标题',b.title,'full')}${selectField('content_form','内容形态',FORM,b.content_form)}${selectField('pool','选题池',{evergreen:'常青研究',timely:'时效事件'},b.pool)}${field('audience','具体读者',b.audience,'full')}${subjectChoices(b)}${area('reader_question','只回答哪一个问题？',b.reader_question,'full')}${area('angle','独立角度 / 对照方法',b.angle)}${area('thesis','一句话结论（用证据支撑）',b.thesis)}${area('original_contribution','你的具体新增贡献',b.original_contribution)}${area('reader_value','读者会得到什么？',b.reader_value)}${numberField('estimated_human_minutes','预计剩余人工分钟',b.estimated_human_minutes)}${numberField('actual_human_minutes','该稿累计人工分钟',b.actual_human_minutes)}${selectField('spoiler_level','剧透等级',{none:'无剧透',mechanics:'机制相关',minor_story:'轻度剧情',major_story:'重大剧情'},b.spoiler_level)}${field('expires_at','截止时间（ISO含时区；常青可留空）',b.expires_at||'')}${area('spoiler_note','剧透提示与标题/封面限制',b.spoiler_note)}${area('author_experience','本人实际体验记录（没有就留空）',b.author_experience)}${area('media_none_reason','不需要配图的原因（有素材可留空）',b.media_none_reason)}${area('missing_evidence','剩余补证事项（每行一项；完成后清除）',b.missing_evidence.join('\n'))}${area('notes','研究备注',b.notes,'full')}<label class="check full"><input type="checkbox" name="scope_confirmed" ${b.scope_confirmed?'checked':''}>我确认该问题属于账号的目标受众，不是无关泛热点。</label></div><div class="form-actions"><button type="submit" class="btn primary">保存简报</button>${button('下一步：研究资料 →','tab-research','ghost')}<small>修改简报会撤销旧审核；已发布的历史版本不会删除。</small></div></form>`;
 }else if(state.tab==='research'){
  $('editorContent').innerHTML=`<div class="row between" style="margin-bottom:19px"><div><h3>依据是什么？先把材料放在这里。</h3><small>发现来源不等于事实来源；机器读取不等于人工核验。</small></div><div class="row">${button('Steam资料补充','steam','ghost')}${button('导出研究包','bundle','ghost')}${button('＋ 添加来源','source','primary')}</div></div><div class="research-grid"><div><div class="section-title" style="margin-top:0"><h3>来源材料 <span class="subtle">${b.sources.length}</span></h3></div><div class="card-list">${b.sources.map(s=>`<article class="source-card"><div class="row between"><h3>${esc(s.title||'未命名来源')}</h3>${tag(s.read_status==='read'?'已读材料':s.read_status==='partial'?'仅摘要':'待读取',s.read_status==='read'?'good':'warn')}</div><p>${esc(s.summary||s.excerpt||'只有URL，没有可供写作的材料。').slice(0,560)}</p><div class="small">${link(s.url)} · ${s.is_primary?'一手材料':'二手 / 待确认'} · ${s.role==='fact'?'事实依据':'发现线索'}</div><small>${esc(s.publisher)} ${s.original_date?'· 原始日期 '+esc(s.original_date):''}</small><div class="row section-gap">${button('编辑材料','source','ghost tiny',`data-id="${s.id}"`)}${button('移除','remove','ghost tiny',`data-kind="sources" data-id="${s.id}"`)}</div></article>`).join('')||'<div class="empty"><p>添加链接、来源摘要或原始访谈片段。不要只粘贴一个AI无法打开的网址。</p></div>'}</div></div><div><div class="section-title" style="margin-top:0"><h3>事实 / 主张 <span class="subtle">${b.claims.length}</span></h3>${button('＋ 建立主张','claim','ghost tiny')}</div><div class="card-list">${b.claims.map(c=>claimCard(c,true)).join('')||'<div class="empty"><p>把需要证明的数字、角色、引语或观察拆成一条条可核验主张。</p></div>'}</div><div class="row section-gap">${button('复算选购清单','curation','ghost tiny')}<small>程序算数量和比例；不跨平台混算。</small></div></div></div><div class="section-title"><h3>图片与演示素材</h3><div class="row">${button('＋ 添加素材链接','asset','ghost tiny')}<label class="btn tiny" style="margin:0">上传截图<input type="file" id="assetUpload" accept="image/png,image/jpeg,image/webp" hidden></label></div></div><div class="asset-grid">${b.assets.map(a=>`<article class="asset-card">${a.local_file?`<img src="/api/assets/${state.mode}/${esc(a.local_file)}" alt="${esc(a.caption||a.title)}">`:''}<h3>${esc(a.title||'素材')}</h3><p>${esc(a.caption||a.usage_note||'说明用途和使用条件')}</p><div class="row">${tag(a.usage_confirmed?'使用已确认':'使用待确认',a.usage_confirmed?'good':'warn')}${link(a.url,'原始素材')}</div><div class="row section-gap">${button('编辑 / 确认','asset','ghost tiny',`data-id="${a.id}"`)}${button('移除','remove','ghost tiny',`data-kind="assets" data-id="${a.id}"`)}</div></article>`).join('')||'<p class="small muted">素材按解释任务选择，不要求凑固定图片数。</p>'}</div>`;
 }else if(state.tab==='draft'){
  const d=draftDefaults(),cache=cached();
  $('editorContent').innerHTML=`<div class="writing-layout"><div class="writing-main">${cache?`<div class="hint warn">发现 ${date(cache.saved_at)} 的浏览器未保存缓存。${cache.base_version!==b.version?'磁盘版本已变化，恢复后请仔细合并。':''} ${button('恢复缓存','recover','ghost tiny')}${button('丢弃缓存','discard-cache','ghost tiny')}</div>`:''}<div class="draft-toolbar">${button('生成待审稿','generate','primary')}${button('复制网页AI资料包','prompt','ghost')}${button('导入AI初稿','import-draft','ghost')}${button('导出研究包','bundle','ghost')}</div><div class="revision-row"><small>历史稿件</small><select id="revisionSelect" aria-label="查看历史稿件"><option value="">当前编辑区</option>${b.drafts.map(x=>`<option value="${x.revision}">版本 ${x.revision} · ${date(x.created_at)}</option>`).join('')}</select><small>${b.drafts.length?'当前最新 v'+b.drafts.at(-1).revision:'尚未保存版本'}</small></div><label for="draftTitle">标题</label><input id="draftTitle" value="${esc(d.title)}"><details><summary>${d.title_candidates.length||0} 个标题候选 · 不预测点击率</summary>${(d.title_candidates||[]).map((t,i)=>`<button class="title-option" data-action="choose-title" data-index="${i}">${esc(t)}</button>`).join('')}</details><label for="draftBody" class="section-gap">正文 · 核心段落可用 [C:主张ID] 回查</label><textarea id="draftBody" placeholder="材料齐备后生成待审稿，或把网页AI生成的内容导入这里。">${esc(d.body_markdown)}</textarea><label for="commentHook" class="section-gap">互动问题（可选）</label><input id="commentHook" value="${esc(d.comment_hook||'')}" placeholder="有自然问题才问，不强行引导争吵。"><div class="editor-status" id="editorSaveStatus">${b.drafts.length?'已读取磁盘版本；修改后请保存新版本':'未保存到磁盘'}</div><div class="form-actions">${button('保存新版本','save-draft','primary')}${button('复制待审文本','copy-draft','ghost')}${button('预览','preview','ghost')}</div></div><aside class="writing-sidebar"><h3>本稿引用的事实</h3><small>请勾选实际使用的主张。下方文字可回查源位置。</small><div class="claims-list section-gap">${b.claims.map(c=>`<label class="check"><input type="checkbox" name="used_claim" value="${c.id}" ${(d.used_claim_ids||[]).includes(c.id)?'checked':''}><span>${esc(c.text.slice(0,75))}</span></label>${claimCard(c,false)}`).join('')||'<div class="hint warn">尚无核心事实，请先到研究资料建立主张。</div>'}</div><div class="divider"></div><h3>发布前检查</h3>${b.publish_gaps.length?`<div class="hint warn"><ul>${b.publish_gaps.slice(0,12).map(g=>`<li>${esc(g)}</li>`).join('')}</ul>${b.publish_gaps.length>12?'<small>其余缺口请在研究资料查看。</small>':''}</div>`:'<div class="hint">结构化检查未发现缺口。仍需人工核对文字语义和素材。</div>'}<div class="check-grid"><label class="check"><input id="checkFacts" type="checkbox">逐条核对标题、正文事实与引用</label><label class="check"><input id="checkMedia" type="checkbox">确认素材来源、用途与使用条件</label><label class="check"><input id="checkSpoiler" type="checkbox">确认标题和封面不泄露关键剧情</label><label class="check"><input id="checkPolicy" type="checkbox">检查平台规则与AI辅助说明，不以系统保证激励资格</label></div>${button('人工审核通过','approve','primary')}<p class="intro">改稿会撤销旧审核。保存新版本后，相关事实保守地转为待复查。</p></aside></div>`;
 }else{renderPublishEditor();}
}
function claimCard(c,tools){const b=state.brief;const urls=c.source_ids.map(id=>b.sources.find(s=>s.id===id)).filter(Boolean);return `<article class="claim-card"><div class="row between">${tag(CLAIM[c.kind]||c.kind)}${tag(c.status==='verified'?'人工已核验':c.status==='conflict'?'存在冲突':'待核验',c.status==='verified'?'good':'warn')}</div>${tools?`<p>${esc(c.text)}</p>`:''}<div class="claim-meta">${esc(c.locator||'缺少段落 / 时间点')}<br><code>${esc(c.id)}</code></div>${urls.map(s=>link(s.url,s.title||'来源')).join('<br>')}${c.verified_at?`<div class="claim-meta">${esc(c.verified_by)} · ${date(c.verified_at)}</div>`:''}<div class="row" style="margin-top:9px">${button('编辑','claim','ghost tiny',`data-id="${c.id}"`)}${c.status!=='verified'?button('我已核对','verify','primary tiny',`data-id="${c.id}"`):''}${tools?button('移除','remove','ghost tiny',`data-kind="claims" data-id="${c.id}"`):''}</div></article>`;}
function renderPublishEditor(){const b=state.brief;$('editorContent').innerHTML=`<div class="hint ${b.approval_valid?'':'warn'}">${b.approval_valid?'当前稿件已通过人工审核。发布前仍会检查时效事实。':'当前版本未获有效审核，或事实已过期。请先回编辑与审核页。'}</div><div class="two-cols section-gap"><section class="panel pad"><h3>安排发布时间</h3><p class="intro">仅记录计划，不自动操作小黑盒。</p><form id="scheduleForm" class="section-gap"><label>计划时间（你的浏览器本地时区）</label><input name="at" type="datetime-local" required><div class="form-actions"><button class="btn primary" ${!b.approval_valid?'disabled':''}>保存排期</button>${button('复制已审核发布文本','copy-approved','ghost')}</div></form></section><section class="panel pad"><h3>登记已发布帖子</h3><p class="intro">去小黑盒手动发布，再贴回真实链接。</p><form id="publishForm" class="section-gap">${field('url','小黑盒帖子分享链接','')}${field('published_at','实际发布时间（ISO含时区）',new Date().toISOString())}<div class="form-actions"><button class="btn primary" ${!b.approval_valid||state.mode==='example'?'disabled':''}>登记发布</button></div></form></section></div><div class="section-title"><h3>发布记录</h3></div>${b.publications.length?b.publications.map(p=>`<section class="panel pad section-gap"><div class="row between"><div><h3>${esc(p.title)}</h3><small>稿件 v${p.draft_revision} · ${date(p.published_at)} · ${link(p.url,'帖子')}</small></div>${button('记录数据','metric','ghost tiny',`data-id="${b.id}" data-pub="${p.id}"`)}</div></section>`).join(''):'<p class="small muted">尚未登记。发布记录不会因为之后改稿而消失。</p>'}<div class="section-title"><h3>操作记录</h3>${button('移到待补证','state','ghost tiny','data-status="needs_research"')}${button('归档选题','state','ghost tiny','data-status="archived"')}</div><div class="panel pad">${b.audit.slice(-12).reverse().map(r=>`<div class="source-row"><span>${esc(auditLabel(r.action))}</span><small>${date(r.at)}</small></div>`).join('')}</div>`;}
function auditLabel(a){return {created:'建立选题',brief_updated_approval_invalidated:'修改简报，撤销旧审核',source_saved:'保存来源',claim_saved_needs_verification:'保存主张，等待核验',claim_verified_by_human:'人工核验事实',asset_saved:'保存素材',new_draft_revision:'保存稿件新版本',human_approved:'人工审核通过',scheduled_manual_posting:'安排手动发布时间',publication_recorded_not_automated:'登记发布记录',metric_snapshot_recorded:'记录观察数据',steam_evidence_added_unverified:'采集Steam资料，待核验'}[a]||a;}
async function mutateResult(data){state.brief=data;state.dirty=false;const scroll=$('editorContent').scrollTop;renderEditor();$('editorContent').scrollTop=scroll;await refresh(false);}
function sourceDialog(id){const s=state.brief.sources.find(x=>x.id===id)||{};modal('添加 / 编辑来源',modalForm('sourceForm',`<input name="id" type="hidden" value="${esc(s.id||'')}">${field('title','材料标题',s.title||'','full')}${field('url','公开来源URL（本人截图材料可留空）',s.url||'','full')}${selectField('source_type','来源类别',{official:'官方资料',interview:'原始访谈',media:'媒体',community:'社区',self:'本人材料',unknown:'待确认'},s.source_type||'unknown')}${selectField('role','本次用途',{discovery:'发现线索',fact:'事实依据'},s.role||'fact')}${field('publisher','原始发布者',s.publisher||'')}${field('original_date','原始发表日期（旧材料保留原日期）',s.original_date||'')}${selectField('read_status','读取程度',{unread:'未读（只有链接）',partial:'仅摘要 / 片段',read:'已阅读材料',failed:'读取失败',needs_access:'需要权限'},s.read_status||'unread')}${field('locator','来源位置 / 视频时间码',s.locator||'')}${area('summary','事实摘要（用自己的整理，不整篇复制他人文章）',s.summary||'','full')}${area('excerpt','必要短摘录（可选，保留原文便于核对）',s.excerpt||'','full')}<label class="check full"><input type="checkbox" name="is_primary" ${s.is_primary?'checked':''}>确认是一手材料（不是多层转述）</label>${area('access_note','访问限制 / 备注',s.access_note||'','full')}`));}
const claimSkeleton={price:{store:'steam',region:'CN',currency:'CNY',sku:'',edition:'',observed_at:'',end_at:null,price_minor:null},rating:{platform:'steam',scope:'matching_query_summary',observed_at:'',positive:null,negative:null,total_reviews:null,filters:{language:'all',review_type:'all',purchase_type:'steam',filter_offtopic_activity:1}},quote:{quote_mode:'translation',original_text:'',original_date:''},role:{person:'',work:'',role:'',as_of:''},detail:{platform:'',version:'',conditions:'',steps:'',asset_ids:[]},design_intent:{},historical_low:{store:'steam',region:'CN',currency:'CNY',sku:'',edition:'',observed_at:'',price_minor:null,historical_evidence:'',history_scope:''},free_offer:{platform:'',region:'',offer_type:'free_to_keep',end_at:''},ranking:{universe:'本次候选池',metric:'',sample_size:null,sort_rule:'',dedupe_rule:'',as_of:'',entity_kind:'game'}};
function claimDialog(id){const c=state.brief.claims.find(x=>x.id===id)||{};modal('建立可核验主张',modalForm('claimForm',`<input name="id" type="hidden" value="${esc(c.id||'')}">${area('text','主张：需要证明的一句话',c.text||'','full')}${selectField('kind','主张类型',CLAIM,c.kind||'fact')}${field('locator','段落、表格字段或视频时间点',c.locator||'')}<div class="full"><label>支撑这条主张的来源（至少一个）</label>${state.brief.sources.map(s=>`<label class="check"><input type="checkbox" name="source_ids" value="${s.id}" ${(c.source_ids||[]).includes(s.id)?'checked':''}>${esc(s.title||s.url)}</label>`).join('')||'<small>请先添加来源。</small>'}</div><div class="full" id="claimStructured">${claimDataEditor(c.kind||'fact',c.data||{})}</div><details class="full"><summary>高级：原始字段JSON（未知扩展字段保留）</summary><textarea name="data" class="code">${esc(JSON.stringify(c.data||{},null,2))}</textarea><small>常用字段以上方表单为准；此处仅用于扩展字段，不需要日常手写JSON。</small></details>${field('valid_until','主张有效期（ISO含时区，可留空）',c.valid_until||'')}${field('conflicts','未解决的冲突（解决后清空）',c.conflicts||'')}${area('notes','核验备注',c.notes||'','full')}<label class="check full"><input name="required" type="checkbox" ${c.required!==false?'checked':''}>这是核心主张，生成和发布前必须核验</label>`));}
function assetDialog(id){const a=state.brief.assets.find(x=>x.id===id)||{};modal('素材说明与使用确认',modalForm('assetForm',`<input name="id" type="hidden" value="${esc(a.id||'')}">${field('title','素材名称',a.title||'','full')}${field('url','原始素材URL / 演示视频URL',a.url||'','full')}${field('publisher','作者 / 发布方',a.publisher||'')}${field('timecode','视频时间码（例如 02:10–02:24）',a.timecode||'')}${selectField('purpose','用途',{cover:'封面',evidence:'事实 / 细节证据',illustration:'说明配图'},a.purpose||'illustration')}${selectField('spoiler_level','素材剧透等级',{none:'无',mechanics:'机制',minor_story:'轻剧情',major_story:'重剧情'},a.spoiler_level||'none')}${area('caption','这张素材具体证明 / 解释什么？',a.caption||'','full')}${area('usage_note','来源和使用条件（不知道则保持待确认）',a.usage_note||'','full')}<label class="check full"><input name="usage_confirmed" type="checkbox" ${a.usage_confirmed?'checked':''}>我已核实本素材的使用条件</label><small class="full">素材ID：${esc(a.id||'保存后生成')}。细节主张可在 asset_ids 中关联这个ID。</small>`));}
function newDialog(){modal('新建一个有价值的问题',modalForm('newForm',`${field('title','选题标题 / 待回答的问题','','full')}${selectField('content_form','内容形态',FORM,'classic')}${selectField('pool','选题池',{evergreen:'常青研究',timely:'时效事件'},'evergreen')}${area('reader_question','读者会关心的具体问题','','full')}`, '建立选题'));}
async function watchJob(id){
 if(state.polling===id)return;state.polling=id;state.jobId=id;setConnection('busy');if(!state.brief)renderView();
 async function poll(){try{const j=await api('/api/jobs/'+id);if($('jobMessage'))$('jobMessage').textContent=j.message;
  if(['done','error','interrupted'].includes(j.status)){state.polling=null;state.jobId=null;setConnection('ready');await refresh();if(j.status!=='done')toast(j.message);else{
   const r=j.result||{};
   if(r.outline||r.gaps?.length){modal('研究简报 / 待写大纲',`<div class="hint warn">${esc(r.message||'材料尚未齐备。这里只生成资料简报，不冒充完成稿。')}</div>${r.gaps?.length?`<ul class="small">${r.gaps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<pre class="codeblock section-gap">${esc(r.outline||'')}</pre>`);}
   else toast(r.message||'任务已完成，请查看来源状态和新增选题。');
   if(state.brief&&!state.dirty){state.brief=await api(modePath('/api/briefs/'+state.brief.id));renderEditor();}
  }return;}
  setTimeout(poll,1200);
 }catch(e){state.polling=null;state.jobId=null;toast(errorText(e));}}
 poll();
}
async function copyToClipboard(text){try{await navigator.clipboard.writeText(text);toast('已复制');}catch{modal('复制文本',`<p class="intro">浏览器限制了剪贴板权限，请在下框中全选复制。</p><textarea id="copyFallback" style="min-height:340px">${esc(text)}</textarea>`);$('copyFallback').focus();$('copyFallback').select();}}
async function saveCurrentDraft(){const data=currentDraftData();if(!data.body_markdown.trim())throw new Error('正文不能为空；资料大纲不应伪装成完成稿。');const key=cacheKey();const result=await put('/api/briefs/'+state.brief.id+'/draft',{expected_version:state.brief.version,draft:data});try{localStorage.removeItem(key);}catch{}await mutateResult(result);toast('已保存新版本到磁盘。修改后的事实需重新核验。');}

const lines=s=>String(s||'').split('\n').map(x=>x.trim()).filter(Boolean);
const formValue=(f,k)=>String(new FormData(f).get(k)||'').trim();
const formCheck=(f,k)=>f.elements.namedItem(k)?.checked===true;
const formNumber=(f,k,nullable=false)=>{const v=formValue(f,k);if(nullable&&v==='')return null;const n=Number(v);if(!Number.isFinite(n))throw new Error(k+' 需要数字');return n;};
const checkedValues=(f,k)=>[...f.querySelectorAll(`input[name="${k}"]:checked`)].map(x=>x.value);
function parseJSON(s){try{return JSON.parse(s);}catch{throw new Error('JSON格式不正确，请检查引号和逗号。');}}
function mustSave(){if(state.dirty)throw new Error('请先保存正在编辑的稿件，再进行此操作。');}
async function switchMode(mode){
 if(state.brief&&state.dirty&&!confirm('尚未保存的稿件将保留在当前浏览器缓存。确认切换资料库？'))return;
 $('editorOverlay').hidden=true;document.body.style.overflow='';state.brief=null;state.dirty=false;state.mode=mode;state.dash=null;state.filterStatus='';state.filterColumn='';state.filterPool='all';await refresh();
}
function importDraftDialog(){modal('导入网页AI / 人工初稿',modalForm('importDraftForm',`<p class="intro full">推荐粘贴研究包约定的JSON，也可粘贴纯正文。导入不代表已核验；所有正文与主张需要人工对应检查。</p>${area('content','JSON或Markdown正文','','full')}<label class="check full"><input name="confirmed" type="checkbox" required>我知道这只是待审初稿，不是系统批准的发布稿。</label>`, '导入为新版本'));}
function subjectDialog(){modal('新增题材',modalForm('subjectForm',`${field('name','名称','','full')}${selectField('kind','实体类型',{game:'游戏',person:'制作人',studio:'开发工作室',publisher:'发行商',group:'集团'},'game')}${selectField('familiarity','本人熟悉程度',{unknown:'未知 / 未体验',researched:'已阅读资料',played:'本人实际玩过'},'unknown')}${area('aliases','别名（每行一个）','')}${area('platform_ids','平台ID JSON（可留空）','{}')}${area('notes','研究备注','','full')}<label class="check full"><input name="confirmed" type="checkbox">我确认了该实体身份（不等于确认每部作品的职务）</label>`));}
async function metricDialog(bid,pid){
 if(!state.brief||state.brief.id!==bid)state.brief=await api(modePath('/api/briefs/'+bid));
 const p=state.brief.publications.find(x=>x.id===pid);if(!p)throw new Error('发布记录不存在');
 modal('记录一次真实表现观察',modalForm('metricForm',`<input type="hidden" name="publication_id" value="${p.id}"><p class="intro full">${esc(p.title)}。拿不到的数字请留空，不是填写0。实际帖子年龄由时间计算。</p>${selectField('window','目标观察窗口',{'24h':'发布24h','72h':'发布72h','7d':'发布7d',custom:'其他时间'},'24h')}${field('observed_at','实际观察时间（ISO含时区）',new Date().toISOString())}${numberField('views','阅读量（可空）','')}${numberField('likes','点赞（可空）','')}${numberField('comments','评论（可空）','')}${numberField('favorites','收藏（可空）','')}${numberField('shares','分享（可空）','')}${numberField('follows','可归因于本帖的关注（可空）','')}${area('source_note','数字来自哪里？','本人后台 / 公开帖子页面')}${area('missing_reason','缺少数据的原因','平台未提供 / 未记录')}${area('comment_quality','评论质量：补充 / 提问 / 纠错 / 玩梗 / 争吵','','full')}`));
}
async function action(name,el){
 const bid=state.brief?.id;const version=state.brief?.version;
 if(name==='run'){const j=await post('/api/run',{mode:state.mode});watchJob(j.id);return;}
 if(name==='new')return newDialog();
 if(name==='topics'||name==='settings'){state.view=name;return renderView();}
 if(name==='needs-research'||name==='evergreen'){state.view='topics';state.filterPool=name==='evergreen'?'evergreen':'all';state.filterStatus=name==='needs-research'?'needs_research':'';return renderView();}
 if(name==='open'||name==='open-publish')return openBrief(el.dataset.id,name==='open-publish'?'publish':'brief');
 if(name==='seeds'){const r=await post('/api/seeds',{});await refresh();toast(`已处理角度种子。重复载入不会新增重复题。`);return;}
 if(name==='example'){await switchMode('example');const j=await post('/api/run',{mode:'example'});return watchJob(j.id);}
 if(name==='offline'){const j=await post('/api/run',{mode:'offline'});return watchJob(j.id);}
 if(name==='close-modal')return closeModal();
 if(name==='subject')return subjectDialog();
 if(name==='import-pack')return modal('导入研究资料包',modalForm('packForm',`<p class="intro full">粘贴 examples 中的导入JSON，或编辑台导出的 research-pack.json。外部核验与素材许可会重置，导入后仍需人工确认。</p>${area('json','研究包JSON','','full')}`,'导入到当前资料库'));
 if(name==='metric')return metricDialog(el.dataset.id,el.dataset.pub);
 if(!bid)throw new Error('请先打开一个选题。');
 if(name==='bundle'){location.href=modePath(`/api/briefs/${bid}/bundle`);return;}
 if(name==='prompt'){const p=await api(modePath(`/api/briefs/${bid}/prompt`));await copyToClipboard(p.instructions+'\n\n'+JSON.stringify(p,null,2));return;}
 if(name==='tab-research'){mustSave();state.tab='research';return renderEditor();}
 if(name==='source'){mustSave();return sourceDialog(el.dataset.id);}
 if(name==='claim'){mustSave();return claimDialog(el.dataset.id);}
 if(name==='asset'){mustSave();return assetDialog(el.dataset.id);}
 if(name==='remove'){mustSave();if(confirm('确认移除？关联的主张和当前稿件将需要重新审核。'))await mutateResult(await api(modePath(`/api/briefs/${bid}/${el.dataset.kind}/${el.dataset.id}`),{method:'DELETE',body:JSON.stringify({expected_version:version})}));return;}
 if(name==='verify'){mustSave();const c=state.brief.claims.find(x=>x.id===el.dataset.id);if(confirm('确认你已经阅读原始材料，并核对了以下主张？\n\n'+c.text)){await mutateResult(await post(`/api/briefs/${bid}/claims/${c.id}/verify`,{expected_version:version,reviewer:state.dash.settings.reviewer_name,confirmed:true}));toast('已记录人工核验。');}return;}
 if(name==='generate'){mustSave();const j=await post(`/api/briefs/${bid}/generate`,{expected_version:version});watchJob(j.id);return;}
 if(name==='save-draft')return saveCurrentDraft();
 if(name==='choose-title'){const t=state.brief.drafts.at(-1)?.title_candidates[Number(el.dataset.index)];if(t){$('draftTitle').value=t;markDirty();}return;}
 if(name==='import-draft'){mustSave();return importDraftDialog();}
 if(name==='copy-approved'||name==='copy-draft'){mustSave();const r=await api(modePath(`/api/briefs/${bid}/copy?approved=${name==='copy-approved'}`));return copyToClipboard(r.text);}
 if(name==='citation'){const c=state.brief.claims.find(c=>c.id===el.dataset.id);if(!c)throw new Error('引用主张不存在');modal('主张与来源定位',claimCard(c,true)+`<pre class="codeblock">${esc(JSON.stringify(c.data,null,2))}</pre>`);return;}
 if(name==='preview'){const d=currentDraftData();modal('文字预览 · 内部引用标记不会写入发布文本',`<article class="read-preview"><h2>${esc(d.title)}</h2>${renderMarkdown(d.body_markdown)}<p>${esc(d.comment_hook)}</p></article>`);return;}
 if(name==='recover'){const c=cached();if(c){if(c.base_version!==state.brief.version&&!confirm('缓存基于旧版本。恢复后请对照磁盘版本核查，是否继续？'))return;$('draftTitle').value=c.draft.title;$('draftBody').value=c.draft.body_markdown;$('commentHook').value=c.draft.comment_hook;document.querySelectorAll('[name=used_claim]').forEach(i=>i.checked=c.draft.used_claim_ids.includes(i.value));markDirty();toast('已恢复到编辑区，尚未保存到磁盘。');}return;}
 if(name==='discard-cache'){if(confirm('仅删除本浏览器缓存，磁盘稿件不会删除。确认？')){localStorage.removeItem(cacheKey());state.dirty=false;renderEditor();}return;}
 if(name==='approve'){mustSave();const r=await post(`/api/briefs/${bid}/approve`,{expected_version:version,reviewer:state.dash.settings.reviewer_name,facts_checked:$('checkFacts').checked,media_checked:$('checkMedia').checked,spoiler_checked:$('checkSpoiler').checked,policy_checked:$('checkPolicy').checked});await mutateResult(r);toast('已记录本次人工审核。发布前仍会重新检查时效事实。');return;}
 if(name==='steam'){mustSave();return modal('获取一个游戏的Steam资料',modalForm('steamForm',`${numberField('appid','Steam AppID','')}<label class="check"><input name="reviews" type="checkbox" checked>读取同口径评价摘要与少量评论样本</label><p class="intro full">只查询选中游戏，不抓全Steam。价格是当前地区和商品快照；读取后仍需人工核验。</p>`,'开始读取'));}
 if(name==='curation'){mustSave();return modal('从最终清单重新计算',modalForm('curationForm',`${selectField('kind','计算方式',{prices:'价格清单：去重、数量、当前最低价',ratings:'同口径Steam推荐率筛选'},'prices')}<div class="full">${state.brief.claims.filter(c=>['price','rating'].includes(c.kind)&&c.status==='verified').map(c=>`<label class="check"><input type="checkbox" name="claim_ids" value="${c.id}">${esc(c.text)}</label>`).join('')||'<p>先补充并核验价格或评价主张。</p>'}</div><p class="intro full">输出只描述选中的候选，不代表全Steam排名；结果也会作为新主张待核验。</p>`,'计算清单'));}
 if(name==='state'){mustSave();if(confirm('确认修改选题状态？当前审核和排期会被取消，但历史稿件和发布记录不删除。'))await mutateResult(await post(`/api/briefs/${bid}/state`,{expected_version:version,status:el.dataset.status}));return;}
}
function normalizeImportedPack(p){
 if(p.format!=='heybox-source-pack-v2')return p;
 if(p.mode==='example'&&state.mode==='live')throw new Error('示例研究包不能导入真实资料库。');const {id,...brief}=p.brief;return {origin_mode:p.mode,brief:{...brief,pool:'evergreen',scope_confirmed:false},sources:(p.source_pack||[]).map(s=>({...s,provenance:'import'})),claims:p.verified_claims||[],assets:p.media||[]};
}
async function handleForm(form){
 const name=form.id;const g=k=>formValue(form,k);const bid=state.brief?.id,v=state.brief?.version;
 if(name==='newForm'){const r=await post('/api/briefs',{title:g('title'),content_form:g('content_form'),column:FC[g('content_form')],pool:g('pool'),reader_question:g('reader_question')});closeModal();await refresh();return openBrief(r.id);}
 if(name==='briefForm'){
  const keys=['title','audience','reader_question','angle','thesis','original_contribution','reader_value','spoiler_note','author_experience','media_none_reason','notes'];const brief=Object.fromEntries(keys.map(k=>[k,g(k)]));Object.assign(brief,{content_form:g('content_form'),column:FC[g('content_form')],pool:g('pool'),scope_confirmed:formCheck(form,'scope_confirmed'),estimated_human_minutes:formNumber(form,'estimated_human_minutes',true),actual_human_minutes:formNumber(form,'actual_human_minutes'),spoiler_level:g('spoiler_level'),expires_at:g('expires_at')||null,missing_evidence:lines(g('missing_evidence')),subject_ids:[...form.querySelectorAll('input[name=subject_ids]:checked')].map(e=>e.value)});await mutateResult(await put(`/api/briefs/${bid}`,{expected_version:v,brief}));toast('简报已保存；变更内容的事实需重新核验。');return;
 }
 if(name==='sourceForm'){const source=Object.fromEntries(['title','url','source_type','role','publisher','read_status','locator','summary','excerpt','access_note'].map(k=>[k,g(k)]));if(g('id'))source.id=g('id');source.original_date=g('original_date')||null;source.is_primary=formCheck(form,'is_primary');const r=await put(`/api/briefs/${bid}/source`,{expected_version:v,source});closeModal();return mutateResult(r);}
 if(name==='claimForm'){const claim={text:g('text'),kind:g('kind'),source_ids:checkedValues(form,'source_ids'),locator:g('locator'),required:formCheck(form,'required'),data:readClaimData(form),valid_until:g('valid_until')||null,conflicts:g('conflicts'),notes:g('notes')};if(g('id'))claim.id=g('id');const r=await put(`/api/briefs/${bid}/claim`,{expected_version:v,claim});closeModal();return mutateResult(r);}
 if(name==='assetForm'){const asset=Object.fromEntries(['title','url','publisher','purpose','caption','timecode','usage_note','spoiler_level'].map(k=>[k,g(k)]));asset.usage_confirmed=formCheck(form,'usage_confirmed');if(g('id')){asset.id=g('id');asset.source_id=state.brief.assets.find(a=>a.id===g('id'))?.source_id||null;}const r=await put(`/api/briefs/${bid}/asset`,{expected_version:v,asset});closeModal();return mutateResult(r);}
 if(name==='importDraftForm'){
  const text=g('content');if(!formCheck(form,'confirmed'))throw new Error('请确认这是待审稿');let draft;
  if(text.startsWith('{')){draft=parseJSON(text);draft.assistance='web_ai_import';}
  else draft={title:state.brief.title,title_candidates:[],body_markdown:text,comment_hook:'',used_claim_ids:state.brief.claims.filter(c=>c.status==='verified').map(c=>c.id),assistance:'web_ai_import'};
  const r=await put(`/api/briefs/${bid}/draft`,{expected_version:v,draft});closeModal();state.tab='draft';return mutateResult(r);
 }
 if(name==='steamForm'){const j=await post(`/api/briefs/${bid}/steam`,{expected_version:v,appid:formNumber(form,'appid'),reviews:formCheck(form,'reviews')});closeModal();return watchJob(j.id);}
 if(name==='curationForm'){const r=await post(`/api/briefs/${bid}/curate`,{expected_version:v,claim_ids:checkedValues(form,'claim_ids'),kind:g('kind')});closeModal();await mutateResult(r.brief);toast('清单已计算，结果作为待核验主张保存。');return;}
 if(name==='scheduleForm'){await mutateResult(await post(`/api/briefs/${bid}/schedule`,{expected_version:v,scheduled_at:new Date(g('at')).toISOString()}));toast('排期已保存，不会自动发布。');return;}
 if(name==='publishForm'){await mutateResult(await post(`/api/briefs/${bid}/publish`,{expected_version:v,url:g('url'),published_at:g('published_at')}));toast('已登记手动发布的帖子。');return;}
 if(name==='metricForm'){
  const metric={publication_id:g('publication_id'),window:g('window'),observed_at:g('observed_at'),source_note:g('source_note'),missing_reason:g('missing_reason'),comment_quality:g('comment_quality')};for(const k of ['views','likes','comments','favorites','shares','follows'])metric[k]=formNumber(form,k,true);
  const r=await post(`/api/briefs/${bid}/metric`,{expected_version:v,metric});closeModal();state.brief=r;if(!$('editorOverlay').hidden)renderEditor();else state.brief=null;await refresh();toast('观察数据已记录，空值保持未知。');return;
 }
 if(name==='subjectForm'){await put('/api/subjects',{name:g('name'),kind:g('kind'),aliases:lines(g('aliases')),platform_ids:parseJSON(g('platform_ids')||'{}'),familiarity:g('familiarity'),notes:g('notes'),confirmed:formCheck(form,'confirmed')});closeModal();return renderView();}
 if(name==='packForm'){const r=await post('/api/import-pack',normalizeImportedPack(parseJSON(g('json'))));closeModal();await refresh();return openBrief(r.id,'research');}
 if(name==='settingsForm'){
  const s={...state.dash.settings};for(const k of ['reviewer_name','audience','country','llm_mode'])s[k]=g(k);for(const k of ['daily_minutes','weekly_minutes','heavy_posts_per_week','daily_posts_max','price_fresh_minutes','min_review_count','max_requests','request_timeout','llm_timeout'])s[k]=formNumber(form,k);
  s.column_mix={buy_smart:formNumber(form,'mix_buy'),classic_rediscovery:formNumber(form,'mix_classic'),behind_the_game:formNumber(form,'mix_behind')};s.subreddits=lines(g('subreddits'));s.official_rss=lines(g('official_rss'));s.watched_apps={};for(const row of lines(g('watched_apps'))){const match=row.match(/^(\d+)\s*=\s*(.+)$/);if(!match)throw new Error('关注游戏请使用 AppID=游戏名，每行一个');s.watched_apps[match[1]]=match[2];}for(const k of Object.keys(s.enabled_sources))s.enabled_sources[k]=formCheck(form,'source_'+k);await put('/api/settings',s);await refresh();toast('设置已保存。');return;
 }
 if(name==='policyForm'){await put('/api/policy',{...state.dash.policy,urls:lines(g('urls')),reviewer:g('reviewer'),checked_at:g('checked_at')||null,ai_note:g('ai_note'),notes:g('notes')});await refresh();toast('人工规则核查备注已保存，不代表系统保证激励资格。');return;}
}
document.addEventListener('click',async e=>{
 const el=e.target.closest('[data-action]');if(el){e.preventDefault();if(el.disabled)return;el.disabled=true;try{await action(el.dataset.action,el);}catch(err){toast(errorText(err));}finally{el.disabled=false;setConnection(state.conn);}return;}
 const nav=e.target.closest('[data-view]');if(nav){state.view=nav.dataset.view;state.filterColumn='';try{await renderView();}catch(err){toast(errorText(err));}return;}
 const col=e.target.closest('[data-column]');if(col){state.view='topics';state.filterColumn=col.dataset.column;state.filterStatus='';state.filterPool='all';await renderView();return;}
 const pool=e.target.closest('[data-pool]');if(pool){state.filterPool=pool.dataset.pool;await renderView();return;}
 const tab=e.target.closest('[data-tab]');if(tab){if(state.dirty&&!confirm('切换会保留浏览器中的未保存稿件缓存。确认继续？'))return;state.dirty=false;state.tab=tab.dataset.tab;renderEditor();}
});
document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target;const b=f.querySelector('button[type=submit],button:not([type])');if(b)b.disabled=true;try{await handleForm(f);}catch(err){toast(errorText(err));}finally{if(b)b.disabled=false;}});
document.addEventListener('input',e=>{
 if(['draftTitle','draftBody','commentHook'].includes(e.target.id))markDirty();
 if(e.target.id==='topicSearch'){state.search=e.target.value;$('topicsTable').innerHTML=topicTable(filtered());}
});
document.addEventListener('change',async e=>{try{
 const el=e.target;
 if(el.id==='workspaceMode')await switchMode(el.value);
 if(el.id==='columnFilter'){state.filterColumn=el.value;$('topicsTable').innerHTML=topicTable(filtered());}
 if(el.id==='statusFilter'){state.filterStatus=el.value;$('topicsTable').innerHTML=topicTable(filtered());}
 if(el.name==='used_claim')markDirty();
 if(el.closest('#claimForm')&&el.name==='kind'){const data=el.form.elements.namedItem('data');if(data.value.trim()==='{}'||confirm('按新的主张类型替换字段？')){data.value='{}';$('claimStructured').innerHTML=claimDataEditor(el.value,{});}}
 if(el.id==='revisionSelect'){const r=state.brief.drafts.find(x=>x.revision===Number(el.value));if(r)modal('只读历史稿件 · v'+r.revision,`<div class="hint">历史版本不可覆盖。需要修改请在当前编辑区保存为新版本。</div><h3 class="section-gap">${esc(r.title)}</h3><pre class="preview-text">${esc(r.body_markdown)}</pre><small>${date(r.created_at)}</small>`);}
 if(el.id==='assetUpload'&&el.files[0]){
  mustSave();const form=new FormData();form.append('file',el.files[0]);form.append('expected_version',state.brief.version);
  const r=await fetch(modePath(`/api/briefs/${state.brief.id}/upload`),{method:'POST',headers:{'X-Heybox-Token':state.meta.csrf_token},body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail||'上传失败');await mutateResult(data);toast('截图已保存在项目磁盘，请补充用途和使用条件。');
 }
}catch(err){toast(errorText(err));}});
$('closeEditor').addEventListener('click',closeEditor);$('closeModal').addEventListener('click',closeModal);
$('returnLive').addEventListener('click',()=>switchMode('live').catch(e=>toast(errorText(e))));
$('connection').addEventListener('click',()=>{health();toast(state.conn==='disconnected'?'请双击 scripts/start-web.command。详细日志：logs/web.log':'本地单人服务。数据来源可用性见采集状态，不等于服务健康状态。');});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{
 if(e.key==='Escape'){if(!$('modalOverlay').hidden)closeModal();else if(!$('editorOverlay').hidden)closeEditor();}
 if(e.key==='Tab'){const host=!$('modalOverlay').hidden?$('modalOverlay'):!$('editorOverlay').hidden?$('editorOverlay'):null;if(!host)return;const nodes=[...host.querySelectorAll('button:not([disabled]),a[href],input:not([type=hidden]):not([disabled]),textarea,select')].filter(n=>n.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
});
(async()=>{try{
 if(location.protocol==='file:')throw new Error('请双击启动脚本，再从本地服务打开。HTML文件本身不能启动后端。');
 state.meta=await api('/api/meta');setConnection('ready');await refresh();await health();
}catch(e){setConnection('disconnected');$('view').innerHTML=empty('先连接本地编辑台',errorText(e));}setInterval(health,5000);})();

// Safe, deliberately small Markdown preview: no embedded HTML execution.
function renderMarkdown(text){
 const inline=line=>esc(line).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[C:([a-zA-Z0-9_-]+)\]/g,'<button class="citation" data-action="citation" data-id="$1">依据 ↗</button>');
 return text.split(/\n\s*\n/).map(block=>{if(/^### /.test(block))return '<h4>'+inline(block.slice(4))+'</h4>';if(/^## /.test(block))return '<h3>'+inline(block.slice(3))+'</h3>';if(/^# /.test(block))return '<h2>'+inline(block.slice(2))+'</h2>';if(/^> /.test(block))return '<blockquote>'+inline(block.slice(2))+'</blockquote>';if(block.split('\n').every(l=>/^[-*] /.test(l)))return '<ul>'+block.split('\n').map(l=>'<li>'+inline(l.slice(2))+'</li>').join('')+'</ul>';return '<p>'+block.split('\n').map(inline).join('<br>')+'</p>';}).join('');
}

const DATA_FIELDS={
 price:[['store','商店'],['region','地区（如CN）'],['currency','币种（如CNY）'],['sku','商品/SKU ID'],['edition','版本'],['price_minor','当前价最小货币单位（人民币分）','number'],['observed_at','本次价格观察时间（ISO含时区）'],['end_at','优惠结束时间（不知道留空）']],
 historical_low:[['store','商店'],['region','地区'],['currency','币种'],['sku','商品/SKU ID'],['edition','版本'],['price_minor','价格最小货币单位','number'],['observed_at','观察时间（ISO含时区）'],['historical_evidence','历史记录的具体出处与定位'],['history_scope','覆盖范围、同商品/地区/币种说明']],
 rating:[['platform','评分平台','select',{steam:'Steam推荐比例',heybox:'小黑盒十分制',metacritic:'Metacritic',other:'其他'}],['scope','统计范围（Steam默认matching_query_summary）'],['observed_at','统计时刻（ISO含时区）'],['positive','推荐数（Steam）','number'],['negative','不推荐数（Steam）','number'],['total_reviews','同口径总评价数（Steam）','number'],['filters.language','评论语言（all / schinese等）'],['filters.review_type','Steam评论类型','select',{all:'全部评价（共同分母）'}],['filters.purchase_type','Steam购买口径','select',{steam:'Steam购买',all:'所有购买来源',non_steam_purchase:'非Steam购买'}],['filters.filter_offtopic_activity','是否过滤跑题活动','select',{'1':'过滤','0':'不排除'}],['scale','非Steam评分量表（如0–10）'],['sample_size','非Steam评价样本量','number']],
 quote:[['quote_mode','引用形式','select',{direct:'原文直引',translation:'译文',paraphrase:'概述'}],['original_date','原始访谈日期'],['original_text','对应的原文短片段','area']],
 role:[['person','制作人姓名'],['work','具体作品'],['role','此作品中的职务'],['as_of','职务来源日期']],
 detail:[['platform','游玩平台'],['version','版本/Build'],['conditions','触发条件'],['steps','复现/观察步骤','area'],['asset_ids','关联的证据素材ID（每行一个）','array']],
 free_offer:[['platform','商店/平台'],['region','地区'],['offer_type','免费类型','select',{free_to_keep:'限时领取后保留',trial:'限时试玩，不保留',f2p:'原本免费游戏'}],['end_at','活动结束时间（ISO含时区）']],
 ranking:[['universe','纳入范围'],['metric','使用的指标'],['sample_size','样本数量','number'],['sort_rule','排序方法'],['dedupe_rule','版本/SKU去重规则'],['as_of','统计时刻'],['entity_kind','排名对象','select',{game:'游戏作品',person:'制作人',studio:'工作室',publisher:'发行商',group:'集团'}]]
};
function claimDataEditor(kind,data){
 const fields=DATA_FIELDS[kind];if(!fields)return '<small>通用事实和编辑推论通常不需要附加字段；在主张与来源定位里说清依据即可。</small>';
 return '<div class="data-form"><h4>核验要点 · '+esc(CLAIM[kind])+'</h4><div class="form-grid">'+fields.map(([key,label,type,opts])=>{const v=key.split('.').reduce((obj,k)=>obj?.[k],data);const name='d_'+key.replace('.','_');const def=kind==='rating'?({'platform':'steam','scope':'matching_query_summary','filters.language':'all','filters.review_type':'all','filters.purchase_type':'steam','filters.filter_offtopic_activity':1}[key]):null;const value=v??def??'';if(type==='select')return selectField(name,label,opts,String(value));if(type==='number')return numberField(name,label,value);if(type==='area'||type==='array')return area(name,label,type==='array'?(v||[]).join('\n'):value,'full');return field(name,label,value);}).join('')+'</div></div>';
}
function readClaimData(form){
 const obj=parseJSON(formValue(form,'data')||'{}');const kind=formValue(form,'kind');for(const [key,,type] of DATA_FIELDS[kind]||[]){const name='d_'+key.replace('.','_');if(!form.elements.namedItem(name))continue;let value=formValue(form,name);if(type==='number')value=value===''?null:Number(value);if(type==='array')value=lines(value);if(key==='filters.filter_offtopic_activity')value=Number(value);if(key==='end_at'&&value==='')value=null;const path=key.split('.');if(path.length===1)obj[key]=value;else{if(typeof obj[path[0]]!=='object'||obj[path[0]]===null)obj[path[0]]={};obj[path[0]][path[1]]=value;}}return obj;
}
